#!/usr/bin/env python3
# luxarch:luxpm-search-before-create hook v4 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Search LuxPM for an existing issue BEFORE creating one.

PreToolUse(mcp__luxpm__luxpm_create_issue): deny the create unless this session has SEARCHED LuxPM
since the last issue it created — `luxpm_semantic_search`, or `luxpm_list_issues` with a `search`
term. Listing by label or state alone is not a search: it answers "what is open", not "has this
already been filed".

**Why a hook and not just the standard.** Agents file first and look never. The owner had to unwind
a batch of duplicate audit issues by hand, and nothing in the fleet's docs, hooks or skills said to
search first. The escalation rules said the opposite ("file it the moment you find it"). A written
rule an agent is never made to follow is how that happened, so the rule has one home
(FLEET-AGENT-CONDUCT-STANDARD, "LuxPM: required practices") and this is what makes it stick.

It needs the TURN, which is why it is a hook: whether a search happened earlier in this session is
not in any file a guard can scan. It reads the session transcript Claude Code hands every hook.

**One search per FILED issue, not per attempt.** A search twenty issues ago says nothing about the
twenty-first, so the window restarts each time an issue is actually filed: a create whose result
says LuxPM created it. A create that was denied, that LuxPM refused (a wrong project_id), or that is
still pending (the one being judged) is not a filed issue and does not restart the window. Any calls
may come between the search and the create.

v1 identified the create being judged by comparing whole inputs with the transcript copy. When the
two differed, it judged the create against itself, and a refused create restarted the window, so an
agent that had searched could not file (search, create refused, search, create DENIED).

v3: the search's own PostToolUse hook (`luxpm-search-mark`) writes a session marker the
moment the search returns, and this hook allows on it before reading the transcript. The transcript
alone raced Claude Code's flush: a search one call earlier was not yet in the file, and 4 of 11 creates
after a search were denied in one session. The transcript stays as the fallback.

Fails OPEN (no transcript, unreadable line): a hook that blocks on its own uncertainty gets switched
off, taking its real catches with it.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _ledger import has_searched, read_event

_CREATE = "mcp__luxpm__luxpm_create_issue"
_SEMANTIC = "mcp__luxpm__luxpm_semantic_search"
_LIST = "mcp__luxpm__luxpm_list_issues"
_FILED = "Created issue"  # LuxPM's own confirmation text for a create that landed


def _blocks(transcript: str) -> list[dict[str, object]]:
    out: list[dict[str, object]] = []
    with open(transcript, encoding="utf-8") as fh:
        for line in fh:
            try:
                entry = json.loads(line)
            except ValueError:
                continue
            msg = entry.get("message") if isinstance(entry, dict) else None
            content = msg.get("content") if isinstance(msg, dict) else None
            out += (
                [b for b in content if isinstance(b, dict)]
                if isinstance(content, list)
                else []
            )
    return out


def _text(content: object) -> str:
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return " ".join(
            _text(c.get("text") if isinstance(c, dict) else c) for c in content
        )
    return ""


def _is_search(name: str, inp: dict[str, object]) -> bool:
    if name == _SEMANTIC:
        return True
    return name == _LIST and bool(str(inp.get("search") or "").strip())


def main() -> int:
    ev = read_event()
    if has_searched():
        return 0  # the search's PostToolUse marker: on disk before this call began
    try:
        current = ev.get("tool_input") if isinstance(ev.get("tool_input"), dict) else {}
        blocks = _blocks(str(ev.get("transcript_path") or ""))
    except Exception:
        return 0  # fail OPEN
    results = {
        str(b.get("tool_use_id")): (bool(b.get("is_error")), _text(b.get("content")))
        for b in blocks
        if b.get("type") == "tool_result"
    }
    # (name, input, filed?) in order; a create counts as filed only when LuxPM said so.
    uses = []
    for b in blocks:
        if b.get("type") != "tool_use":
            continue
        name = str(b.get("name", ""))
        raw = b.get("input")
        inp: dict[str, object] = raw if isinstance(raw, dict) else {}
        err, text = results.get(str(b.get("id")), (True, ""))
        uses.append((name, inp, name == _CREATE and not err and _FILED in text))
    last_filed = max((i for i, (_, _, filed) in enumerate(uses) if filed), default=-1)
    if any(_is_search(n, inp) for n, inp, _ in uses[last_filed + 1 :]):
        return 0
    title = str((current or {}).get("title") or (current or {}).get("text") or "")[:120]
    print(
        "DENIED: search LuxPM for an existing issue before filing this one.\n"
        f"You are about to file: {title!r}\n"
        "One `luxpm_semantic_search` (or `luxpm_list_issues(search=...)`) since the last issue you\n"
        "actually filed is enough; other calls in between are fine, and a create that was denied or\n"
        "refused does not need a new search. If a match exists, add to it with `luxpm_log_activity`\n"
        "instead of filing a duplicate. FLEET-AGENT-CONDUCT-STANDARD, 'LuxPM: required practices'.",
        file=sys.stderr,
    )
    return 2


if __name__ == "__main__":
    sys.exit(main())
