#!/usr/bin/env python3
# luxarch:luxpm-clear-ledger hook v2 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Clear the commit ledger once the work is tracked in LuxPM.

PostToolUse: an activity log, a work log, OR **closing the issue** — all three are tracking the work,
and the stop guard's own message offers all three:

    Log them (luxpm_create_activity / luxpm_log_work, or close the issue) before finishing

Closing was the one it did not honour, so a turn that closed its ticket with a full summary still got
blocked. That is LUXSIGNAL-20 in a sibling hook: a message promising an escape the code never
implemented. The asymmetry that ticket identified applies — closing the issue is state the agent
legitimately controls, so honouring it is honest rather than a loophole.

A bare `update_issue` does NOT clear: bumping progress or editing a description is not completing the
work. The state has to actually move to done/cancelled.
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _ledger import read_ledger, write_ledger

# A comment is a first-class response, so it records the work exactly as an activity does — it was
# missing here, which meant answering a ticket with the tool LuxPM documents for that purpose left
# the ledger dirty and the Stop hook blocking a turn that HAD tracked itself.
_LOGGING_TOOLS = ("luxpm_create_activity", "luxpm_log_work", "luxpm_add_comment")
_CLOSED_STATES = ("done", "cancelled")


def _decide() -> tuple[str, str]:
    """What this tool call proves about the ledger.

    `("all", "")` — the work is recorded; clear everything.
    `("sha", <sha>)` — ONE commit was attached to an issue; clear only that one. `luxpm_link_commit`
    names the exact sha the ledger is complaining about, so clearing the whole ledger on it would
    mark four unlinked commits as tracked because a fifth was. Precision is available here, so the
    honest thing is to use it.
    `("none", "")` — touched the issue without recording the work.
    """
    try:
        ev = json.load(sys.stdin)
    except Exception:
        return (
            "all",
            "",
        )  # can't tell → behave as before rather than trapping the turn
    tool = ev.get("tool_name") or ""
    if any(t in tool for t in _LOGGING_TOOLS):
        return ("all", "")
    if "luxpm_link_commit" in tool:
        sha = str((ev.get("tool_input") or {}).get("sha") or "").strip()
        return ("sha", sha) if sha else ("none", "")
    if "luxpm_update_issue" in tool:
        state = str((ev.get("tool_input") or {}).get("state") or "").lower()
        return ("all", "") if any(c in state for c in _CLOSED_STATES) else ("none", "")
    return ("none", "")


def _same_commit(a: str, b: str) -> bool:
    """Shas match if either is a prefix of the other — the ledger may hold a short sha."""
    a, b = a.strip().lower(), b.strip().lower()
    n = min(len(a), len(b))
    return bool(n >= 7 and a[:n] == b[:n])


def main() -> int:
    kind, sha = _decide()
    entries = read_ledger()
    if not entries or kind == "none":
        return 0
    if kind == "all":
        write_ledger([])
        print("LuxPM: work tracked — commit ledger cleared.", file=sys.stderr)
        return 0
    keep = [e for e in entries if not _same_commit(str(e.get("sha") or ""), sha)]
    if len(keep) != len(entries):
        write_ledger(keep)
        left = f"{len(keep)} still unlogged" if keep else "ledger clear"
        print(f"LuxPM: commit {sha[:7]} linked — {left}.", file=sys.stderr)
    return 0


sys.exit(main())
