#!/usr/bin/env python3
# luxarch:luxpm-search-mark hook v2 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Record that this session SEARCHED LuxPM, the moment the search returns.

PostToolUse(luxpm_semantic_search | luxpm_list_issues | luxpm_create_issue):
- a search (`luxpm_semantic_search`, or `luxpm_list_issues` with a `search` term) sets this session's
  marker;
- an issue actually FILED (LuxPM's "Created issue" confirmation) clears it, so the next create needs a
  new search.

luxpm-search-before-create reads the marker. It used to read only the transcript, which Claude Code
had not always flushed when the next PreToolUse hook ran: the search one call earlier was missing, and
the create was denied (4 of 11 in one session). A marker written by the search's own PostToolUse hook
is on disk before the next tool call begins.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _ledger import clear_searched, mark_searched, read_event

_SEMANTIC = "mcp__luxpm__luxpm_semantic_search"
_LIST = "mcp__luxpm__luxpm_list_issues"
_CREATE = "mcp__luxpm__luxpm_create_issue"
_FILED = "Created issue"


def main() -> int:
    ev = read_event()
    tool = str(ev.get("tool_name") or "")
    raw = ev.get("tool_input")
    inp: dict[str, object] = raw if isinstance(raw, dict) else {}
    if tool == _SEMANTIC or (tool == _LIST and str(inp.get("search") or "").strip()):
        mark_searched()
    elif tool == _CREATE and _FILED in str(ev.get("tool_response") or ""):
        clear_searched()
    return 0


if __name__ == "__main__":
    sys.exit(main())
