#!/usr/bin/env python3
# luxarch:no-suppression hook v3 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Deny a BARE lint/type suppression — evidence is required, prohibition is not the fleet idiom.

Fleet rule: when a guard fires you fix the code or escalate; you never silence the check
(FLEET-AGENT-CONDUCT-STANDARD #7). But everywhere else the fleet demands EVIDENCE rather than
forbidding outright — the `# <slug>: <reason>` site waiver, `[allowlist].ruff` with an `evidence`
field, `[rules.deferred]` with a written line. A blanket deny was stricter than the standard and
offered no honest way through, which is the same defect unpushed-stop-guard once had.

So a suppression carrying a REASON on the same line passes (the gate still adjudicates it); a bare
one is denied. Found by dogfooding: the blanket version blocked edits to this very hook set, because
a hook legitimately needs a suppression for its import shape — and then blocked the fix to itself.

PreToolUse(Edit|Write): deny when the edit adds a suppression with no reason after it.

v3: Swift too, so an iOS repo (luxios installs this same set) is held to the same bar. Swift's
idiom differs and is luxios's (FLEET-IOS-STANDARD "Site waivers", arch-check §7): the reason is a
`// <why>` comment on the line DIRECTLY ABOVE a clean `swiftlint:disable` directive, because
SwiftLint reads every token after the rule names as another rule name. So a Swift disable is bare
when the line above is not such a comment, or when it carries an inline `—`/`--` reason. The line
above is often outside an Edit's `old_string`, so for an Edit the hook reads the file and judges
the whole file before and after; judging the fragment alone would deny every correct waiver whose
reason was already in place.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _cmdtext import edited, write_targets

# A suppression marker, its optional rule code, then whatever the author wrote after it.
# The code list is CODES and separators — never prose. `[\w, -]*` included the space AND the hyphen,
# so `
# code group, leaving an empty tail and counting as BARE. The hook then denied the evidenced form
# while its own message promised "write the reason on the same line … it passes here" — the
# shape this hook family has hit before, an escape the code never implemented. A
# bracketed code may contain hyphens (`# type: ignore[arg-type]`), so brackets are matched whole.
SUPPRESSION = re.compile(
    r"#\s*(?:noqa|type:\s*ignore|ruff:\s*noqa|mypy:\s*ignore|pylint:\s*disable|nosec)"
    r"(?::?\s*(?:\[[^\]\n]*\])?\s*(?:\w+[,\s]*)*)?(?P<tail>[^\n]*)"
)
# A reason is prose after the marker/code: a second `#` comment, or a dash/colon lead-in.
REASON = re.compile(r"#\s*\S|[-—:]\s*\S")


# Quoted spans in the CONTENT being written. A suppression marker inside a string literal is DATA —
# a pattern a codemod matches on, a docstring example, a test fixture — not a directive silencing a
# checker. Reading content raw blocked a script whose purpose was REMOVING dead suppressions; that
# is the same mistake the Bash hooks made (0.158.1) and the same fix: mask, then match.
_TRIPLE = re.compile(r"('{3}|\"{3})(?:.|\n)*?\1")
_SINGLE = re.compile(r"'[^'\n]*'|\"[^\"\n]*\"")


def _unquoted(text: str) -> str:
    """`text` with string literals blanked (length preserved), so only real comments remain."""

    def blank(m: re.Match[str]) -> str:
        return "".join("\n" if c == "\n" else " " for c in m.group(0))

    return _SINGLE.sub(blank, _TRIPLE.sub(blank, text or ""))


def _bare(text: str) -> int:
    """How many suppressions in `text` carry NO written reason."""
    return sum(
        1
        for m in SUPPRESSION.finditer(_unquoted(text))
        if not REASON.search(m.group("tail") or "")
    )


# arch-check §7, line for line. A directive is a `// swiftlint:disable…` COMMENT (text in a string
# literal is not one). It is waived only by a `//` comment directly above it that is real prose: it
# has a letter, it is not a `///` doc, a `// MARK:` or another swiftlint directive. The directive
# itself carries rule names only (`[a-z_]+`); any other token after them is an inline reason, which
# SwiftLint reads as more rule names, and a `:` in one silently voids the waiver.
# (`\/\/` too: the comment as a `sed` replacement escapes its slashes.)
_SWIFT_DIRECTIVE = re.compile(
    r"(?://|\\/\\/)\s*swiftlint:disable(?::(?:next|this|previous))?(?P<rules>[^\n]*)"
)
_SWIFT_IS_DIRECTIVE = re.compile(r"^\s*//\s*swiftlint:")
_SWIFT_REASON = re.compile(r"^\s*//(?!/)(?!\s*MARK\b)[^\n]*[A-Za-z]")
_SWIFT_RULE = re.compile(r"^[a-z_]+$")


def _swift_bare(text: str) -> int:
    """How many `swiftlint:disable` directives in `text` carry no reason line above them."""
    n, prev = 0, ""
    for line in (text or "").splitlines():
        m = _SWIFT_DIRECTIVE.search(line)
        if m:
            inline = any(not _SWIFT_RULE.match(t) for t in m.group("rules").split())
            reasoned = bool(
                _SWIFT_REASON.search(prev)
            ) and not _SWIFT_IS_DIRECTIVE.search(prev)
            if inline or not reasoned:
                n += 1
        prev = line
    return n


_READ_ERRORS = (OSError, ValueError)


def _whole_file(
    path: str, old: str, new: str, *, write: bool, replace_all: bool
) -> tuple[str, str]:
    """The whole file before and after the edit, so the line ABOVE an edited directive is seen.

    An Edit applies `old` -> `new` once, or everywhere with `replace_all` (v3 applied it once, so a
    second site's bare disable went unjudged). A Write replaces the whole file, so "before" is the
    file as it is (v3 used "", which counted a pre-existing bare disable as added by the Write). A
    shell write, or a file that cannot be read, falls back to the fragments.
    """
    try:
        body = Path(path).read_text(encoding="utf-8")
    except _READ_ERRORS:
        return old, new
    if write:
        return body, new
    if not old or old not in body:
        return old, new
    return body, body.replace(old, new) if replace_all else body.replace(old, new, 1)


def main() -> int:
    try:
        ev = json.load(sys.stdin)
    except Exception:
        return 0
    path, old, new = edited(ev)
    ti = ev.get("tool_input") or {}
    cmd = ti.get("command") or ""
    swift = path.endswith(".swift") or any(
        t.endswith(".swift") for t in write_targets(cmd)
    )
    if swift or (not path and "swiftlint:disable" in new):
        before, after = (
            _whole_file(
                path,
                old,
                new,
                write="content" in ti,
                replace_all=bool(ti.get("replace_all")),
            )
            if path and not cmd
            else (old, new)
        )
        if _swift_bare(after) <= _swift_bare(before):
            return 0
        print(
            "DENIED: this edit adds a `swiftlint:disable` with no reason above it.\n"
            "Fix the underlying code, or escalate the rule as wrong. If the waiver IS warranted, "
            "put the reason in a `// <why>` comment on the line DIRECTLY ABOVE a clean directive "
            "(rule names only, no inline `—` reason: SwiftLint reads trailing words as rule "
            'names). See FLEET-IOS-STANDARD "Site waivers" in luxios.',
            file=sys.stderr,
        )
        return 2
    if _bare(new) <= _bare(old):
        return 0
    print(
        "DENIED: this edit adds a BARE lint/type suppression.\n"
        "Fix the underlying code, or escalate the rule as wrong — a silenced check is how a real "
        "defect ships green. If the suppression IS warranted, write the reason on the same line "
        "(that is the fleet's evidence idiom, and it passes here); for a rule-level false positive "
        "the OWNER carves it out in [allowlist].ruff with code+file+match+evidence.",
        file=sys.stderr,
    )
    return 2


sys.exit(main())
