#!/usr/bin/env python3
# luxarch:no-test-weakening hook v2 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""Deny weakening a test to make a suite pass (skip/xfail markers, deleted assertions).

A skipped test reads as a pass. `24 passed, 21 skipped` presenting as coverage is the most
dangerous line in FLEET-VERIFICATION-STANDARD — a suite that can't fail proves nothing. When
a test fails you fix the code or fix a genuinely-wrong test with the owner; you never mark it
skip/xfail to get to green.

PreToolUse(Edit|Write|Bash): deny when an edit to a test file ADDS a skip/xfail marker.

v2: Swift's markers too, so an iOS repo (luxios installs this same set) is held to the same bar:
XCTest's `XCTSkip`/`XCTSkipIf`/`XCTSkipUnless` and `XCTExpectFailure` (its xfail), and Swift
Testing's `.disabled` trait and `withKnownIssue` (its xfail). v1 knew only pytest/unittest, so a
skipped Swift test passed this hook untouched.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _cmdtext import edited

WEAKEN = re.compile(
    r"@pytest\.mark\.(?:skip|xfail)\b|pytest\.skip\(|@unittest\.skip|\.skip\s*=\s*True"
    r"|\bXCTSkip(?:If|Unless)?\s*\(|\bXCTExpectFailure\s*[({]|\bwithKnownIssue\s*[({]"
    r"|@(?:Test|Suite)\s*\((?:[^()]|\([^()]*\))*?\.disabled\b"
    r"|\.enabled\s*\(\s*if:\s*false\b"
    r"|\bx(?:it|describe|context)\s*\(|\bpending\s*\(",
    re.S,
)
# A test file by its path: pytest's `test`, XCTest's `Tests`, Quick/Nimble's `Spec`.
TEST_PATH = re.compile(r"test|spec", re.I)


def main() -> int:
    try:
        ev = json.load(sys.stdin)
    except Exception:
        return 0
    # v2: read through `edited()`, so a heredoc or `sed -i` into a test file is judged like an Edit.
    # v1 read only Edit/Write fields and was bound to `Edit|Write`, so Bash wrote a skip unseen.
    path, old, new = edited(ev)
    if not TEST_PATH.search(path):
        return 0
    if len(WEAKEN.findall(new)) <= len(WEAKEN.findall(old)):
        return 0
    print(
        "DENIED: this edit skips/xfails a test.\n"
        "A skipped test reads as a pass — that is the hollow green. Fix the code under test, "
        "or take a genuinely-wrong test to the owner. If the skip is legitimate (an external "
        "dependency that truly cannot run here), say so and let the owner decide.",
        file=sys.stderr,
    )
    return 2


sys.exit(main())
