"""baseline schema

Revision ID: a2d380f58938
Revises: 006
Create Date: 2026-09-05 22:33:00.169233

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a2d380f58938'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activity_type', sa.Enum('capture_success', 'capture_failed', 'camera_online', 'camera_offline', 'timelapse_started', 'timelapse_completed', 'timelapse_failed', 'service_started', 'service_stopped', 'web_request', 'error', name='activitytype', native_enum=False, length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=True),
    sa.Column('camera_safe_name', sa.String(length=255), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index('ix_activities_camera_timestamp', ['camera_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_activities_type_timestamp', ['activity_type', 'timestamp'], unique=False)

    op.create_table('backup_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retention', sa.Integer(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('backup_dir', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('safe_name', sa.String(length=255), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=True),
    sa.Column('model_key', sa.String(length=32), nullable=False),
    sa.Column('video_mode', sa.String(length=32), nullable=False),
    sa.Column('hdr_type', sa.String(length=16), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('is_recording', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('supports_full_hd_snapshot', sa.Boolean(), nullable=False),
    sa.Column('has_hdr', sa.Boolean(), nullable=False),
    sa.Column('has_mic', sa.Boolean(), nullable=False),
    sa.Column('has_speaker', sa.Boolean(), nullable=False),
    sa.Column('smart_detect_types', sqlite.JSON(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_capture_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_captures', sa.Integer(), nullable=False),
    sa.Column('failed_captures', sa.Integer(), nullable=False),
    sa.Column('capture_method', sa.Enum('auto', 'api', 'rtsp', 'protect_historical', name='capturemethod', native_enum=False, length=32), nullable=False),
    sa.Column('rtsp_quality', sa.String(length=16), nullable=False),
    sa.Column('enabled_intervals', sqlite.JSON(), nullable=True),
    sa.Column('api_max_resolution', sa.String(length=32), nullable=True),
    sa.Column('rtsp_max_resolution', sa.String(length=32), nullable=True),
    sa.Column('recommended_method', sa.Enum('auto', 'api', 'rtsp', 'protect_historical', name='capturemethod', native_enum=False, length=32), nullable=True),
    sa.Column('first_discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cameras_camera_id'), ['camera_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_cameras_safe_name'), ['safe_name'], unique=False)

    op.create_table('fetch_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('intervals', sqlite.JSON(), nullable=True),
    sa.Column('default_capture_method', sa.Enum('auto', 'api', 'rtsp', 'protect_historical', name='capturemethod', native_enum=False, length=32), nullable=False),
    sa.Column('default_rtsp_quality', sa.String(length=16), nullable=False),
    sa.Column('api_key', sa.String(length=256), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_delay', sa.Integer(), nullable=False),
    sa.Column('request_timeout', sa.Integer(), nullable=False),
    sa.Column('high_quality_snapshots', sa.Boolean(), nullable=False),
    sa.Column('rtsp_output_format', sa.String(length=8), nullable=False),
    sa.Column('png_compression_level', sa.Integer(), nullable=False),
    sa.Column('rtsp_capture_timeout', sa.Integer(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('rate_limit_buffer', sa.Float(), nullable=False),
    sa.Column('min_offset_seconds', sa.Integer(), nullable=False),
    sa.Column('max_offset_seconds', sa.Integer(), nullable=False),
    sa.Column('camera_refresh_interval', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('camera_safe_name', sa.String(length=255), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.Enum('live_daily', 'historical', 'historical_combined', name='jobtype', native_enum=False, length=32), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_window_start', sa.Time(), nullable=True),
    sa.Column('daily_window_end', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('current_frame', sa.Integer(), nullable=False),
    sa.Column('total_frames', sa.Integer(), nullable=False),
    sa.Column('current_image', sa.String(length=512), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('keep_images', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('output_file', sa.String(length=512), nullable=True),
    sa.Column('result_details', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_camera_safe_name'), ['camera_safe_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_job_id'), ['job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_jobs_status_completed', ['status', 'completed_at'], unique=False)
        batch_op.create_index('ix_jobs_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_jobs_status_started', ['status', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_target_date'), ['target_date'], unique=False)

    op.create_table('scheduler_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('run_time', sa.Time(), nullable=False),
    sa.Column('days_ago', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('captured', 'historical', name='schedulesource', native_enum=False, length=32), nullable=False),
    sa.Column('enabled_cameras', sqlite.JSON(), nullable=True),
    sa.Column('enabled_intervals', sqlite.JSON(), nullable=True),
    sa.Column('concurrent_jobs', sa.Integer(), nullable=False),
    sa.Column('keep_images', sa.Boolean(), nullable=False),
    sa.Column('recreate_existing', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('frame_rate', sa.Integer(), nullable=False),
    sa.Column('crf', sa.Integer(), nullable=False),
    sa.Column('preset', sa.String(length=16), nullable=False),
    sa.Column('pixel_format', sa.String(length=16), nullable=False),
    sa.Column('ffmpeg_timeout', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('auth_source', sa.String(length=32), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('captures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_db_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('camera_safe_name', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('capture_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capture_date', sa.Date(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed', name='capturestatus', native_enum=False, length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('capture_method', sa.Enum('auto', 'api', 'rtsp', 'protect_historical', name='capturemethod', native_enum=False, length=32), nullable=True),
    sa.Column('capture_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['camera_db_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('captures', schema=None) as batch_op:
        batch_op.create_index('ix_captures_camera_date', ['camera_safe_name', 'capture_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_captures_camera_db_id'), ['camera_db_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_captures_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index('ix_captures_camera_id_date', ['camera_id', 'capture_date'], unique=False)
        batch_op.create_index('ix_captures_camera_id_interval', ['camera_id', 'interval'], unique=False)
        batch_op.create_index('ix_captures_camera_id_timestamp', ['camera_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_captures_camera_interval', ['camera_safe_name', 'interval'], unique=False)
        batch_op.create_index(batch_op.f('ix_captures_camera_safe_name'), ['camera_safe_name'], unique=False)
        batch_op.create_index('ix_captures_camera_timestamp', ['camera_safe_name', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_captures_capture_date'), ['capture_date'], unique=False)
        batch_op.create_index('ix_captures_date_interval', ['capture_date', 'interval'], unique=False)
        batch_op.create_index(batch_op.f('ix_captures_interval'), ['interval'], unique=False)
        batch_op.create_index(batch_op.f('ix_captures_status'), ['status'], unique=False)
        batch_op.create_index('ix_captures_status_timestamp_id', ['status', 'timestamp', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_captures_timestamp'), ['timestamp'], unique=False)

    op.create_table('timelapses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_db_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('camera_safe_name', sa.String(length=255), nullable=False),
    sa.Column('timelapse_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('frame_count', sa.Integer(), nullable=False),
    sa.Column('frame_rate', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='timelapsestatus', native_enum=False, length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['camera_db_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timelapses', schema=None) as batch_op:
        batch_op.create_index('ix_timelapses_camera_date', ['camera_safe_name', 'timelapse_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_timelapses_camera_db_id'), ['camera_db_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timelapses_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index('ix_timelapses_camera_id_date', ['camera_id', 'timelapse_date'], unique=False)
        batch_op.create_index('ix_timelapses_camera_id_interval', ['camera_id', 'interval'], unique=False)
        batch_op.create_index('ix_timelapses_camera_interval', ['camera_safe_name', 'interval'], unique=False)
        batch_op.create_index(batch_op.f('ix_timelapses_camera_safe_name'), ['camera_safe_name'], unique=False)
        batch_op.create_index('ix_timelapses_date_interval', ['timelapse_date', 'interval'], unique=False)
        batch_op.create_index(batch_op.f('ix_timelapses_interval'), ['interval'], unique=False)
        batch_op.create_index(batch_op.f('ix_timelapses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_timelapses_timelapse_date'), ['timelapse_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timelapses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timelapses_timelapse_date'))
        batch_op.drop_index(batch_op.f('ix_timelapses_status'))
        batch_op.drop_index(batch_op.f('ix_timelapses_interval'))
        batch_op.drop_index('ix_timelapses_date_interval')
        batch_op.drop_index(batch_op.f('ix_timelapses_camera_safe_name'))
        batch_op.drop_index('ix_timelapses_camera_interval')
        batch_op.drop_index('ix_timelapses_camera_id_interval')
        batch_op.drop_index('ix_timelapses_camera_id_date')
        batch_op.drop_index(batch_op.f('ix_timelapses_camera_id'))
        batch_op.drop_index(batch_op.f('ix_timelapses_camera_db_id'))
        batch_op.drop_index('ix_timelapses_camera_date')

    op.drop_table('timelapses')
    with op.batch_alter_table('captures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_captures_timestamp'))
        batch_op.drop_index('ix_captures_status_timestamp_id')
        batch_op.drop_index(batch_op.f('ix_captures_status'))
        batch_op.drop_index(batch_op.f('ix_captures_interval'))
        batch_op.drop_index('ix_captures_date_interval')
        batch_op.drop_index(batch_op.f('ix_captures_capture_date'))
        batch_op.drop_index('ix_captures_camera_timestamp')
        batch_op.drop_index(batch_op.f('ix_captures_camera_safe_name'))
        batch_op.drop_index('ix_captures_camera_interval')
        batch_op.drop_index('ix_captures_camera_id_timestamp')
        batch_op.drop_index('ix_captures_camera_id_interval')
        batch_op.drop_index('ix_captures_camera_id_date')
        batch_op.drop_index(batch_op.f('ix_captures_camera_id'))
        batch_op.drop_index(batch_op.f('ix_captures_camera_db_id'))
        batch_op.drop_index('ix_captures_camera_date')

    op.drop_table('captures')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('scheduler_settings')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_target_date'))
        batch_op.drop_index('ix_jobs_status_started')
        batch_op.drop_index('ix_jobs_status_created')
        batch_op.drop_index('ix_jobs_status_completed')
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_jobs_job_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_camera_safe_name'))

    op.drop_table('jobs')
    op.drop_table('fetch_settings')
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cameras_safe_name'))
        batch_op.drop_index(batch_op.f('ix_cameras_camera_id'))

    op.drop_table('cameras')
    op.drop_table('backup_settings')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index('ix_activities_type_timestamp')
        batch_op.drop_index(batch_op.f('ix_activities_timestamp'))
        batch_op.drop_index('ix_activities_camera_timestamp')
        batch_op.drop_index(batch_op.f('ix_activities_camera_id'))
        batch_op.drop_index(batch_op.f('ix_activities_activity_type'))

    op.drop_table('activities')
    # ### end Alembic commands ###
