# luxarch:migration-chain verifier v2 — DO NOT edit the marker line above (repo.migrations_build_schema finds it).
#
# WHY THIS FILE EXISTS
# The other emitted asserter, `--emit schema-drift`, compares your models to a LIVE database and fails
# only on DESTRUCTIVE ops — because there an additive diff usually means "a migration is owed", not
# "something is broken". That is the right policy for THAT question. It is the WRONG policy for a
# different one this file asks: does the migration chain BUILD what the models describe, from EMPTY?
#
# It structurally cannot be caught elsewhere. The canonical test harness (`luxlint --emit-config
# conftest`) builds its schema from `Base.metadata.create_all` — correct for suite speed and isolation,
# and it means the suite NEVER exercises a migration. So `alembic upgrade head` can fail on its very
# first revision — a baseline autogenerated against a create_all DB that captured a one-constraint diff
# instead of a schema, with 34 revisions stacked on a root that creates zero tables — while `make check`
# stays green for months. No new developer, no fresh CI DB, no restore-from-empty can be provisioned,
# and nothing warns until someone tries. (LUXTASTE-285: proven, then escalated as LUXTASTE-286.)
#
# WHAT THIS DOES
# Run it against a THROWAWAY database that has JUST been migrated to head for real (see wiring). It diffs
# the resulting schema against `Base.metadata` and FAILS ON ANY STRUCTURAL DIFF — additive included.
# That is deliberately stricter than schema-drift: here a missing table shows up as `add_table` (an
# ADDITIVE op), and a destructive-only check would wave it through — which is exactly the LUXTASTE-285
# shape sailing past the guard closest to it. Comment-only diffs are still ignored (a check that cries
# about cosmetics gets skipped).
#
# HOW TO WIRE IT (see: FLEET-MAKEFILE-STANDARD "the migration-chain gate")
#   1) Save as scripts/verify_migration_chain.py (or anywhere your `db-verify` target runs it).
#   2) Point METADATA_IMPORT at the package that imports EVERY model (so Base.metadata is complete — see
#      the note below) and DB_URL_ENV at the env var holding the throwaway DB's URL.
#   3) Add a `db-verify` target that, against a FRESH EMPTY DB (never the migrated test DB the suite uses
#      — that one is create_all-built, so the diff would be near-vacuous): creates it, runs `alembic
#      upgrade head`, then runs this script; and add `db-verify` to `check`. luxarch EMITS this and gates
#      that it is wired (repo.migrations_build_schema); it can never RUN it (it has no DB).
from __future__ import annotations

import importlib
import os
import sys
from typing import Any

# --- EDIT THIS ---------------------------------------------------------------------------------------
# The declarative Base, imported from the PACKAGE that registers every model (its `__init__` imports all
# model modules and re-exports Base). Do NOT point at a bare `base_model`: that Base's metadata reflects
# only whatever models happened to be imported by this script's import chain, so every unimported table
# reads as a false "remove_table" — the exact trap that nearly shipped a baseline missing three tables.
METADATA_IMPORT = "app.models:Base"
# The env var that holds the throwaway (freshly migrated) DB URL. Sync and async drivers both work.
DB_URL_ENV = "VERIFY_DATABASE_URL"
# -----------------------------------------------------------------------------------------------------


def _load(path: str) -> object:
    mod, _, attr = path.partition(":")
    if not attr:
        raise ValueError(f"expected 'module:attribute', got {path!r}")
    obj: object = importlib.import_module(mod)
    for part in attr.split("."):
        obj = getattr(obj, part)
    return obj


def _metadata(obj: object) -> object:
    return getattr(
        obj, "metadata", obj
    )  # a declarative Base has .metadata; a MetaData is itself


def _op_name(diff: object) -> str:
    # compare_metadata returns entries that are either an op-tuple or a LIST of op-tuples.
    if isinstance(diff, list):
        return _op_name(diff[0]) if diff else ""
    return str(diff[0]) if isinstance(diff, tuple) and diff else str(diff)


def _compare_sync(sync_conn, metadata) -> list[Any]:  # type: ignore[no-untyped-def]
    from alembic.autogenerate import compare_metadata
    from alembic.migration import MigrationContext

    ctx = MigrationContext.configure(sync_conn, opts={"compare_type": True})
    return list(compare_metadata(ctx, metadata))


def _diff(url: str, metadata: object) -> list[Any]:
    """Own the engine lifecycle end-to-end (no shared pool, no NullPool) — same reason as schema-drift."""
    from sqlalchemy import make_url

    if make_url(url).get_dialect().is_async:
        import asyncio

        from sqlalchemy.ext.asyncio import create_async_engine

        async def _run() -> list[Any]:
            engine = create_async_engine(url)
            try:
                async with engine.connect() as conn:
                    return await conn.run_sync(lambda c: _compare_sync(c, metadata))
            finally:
                await engine.dispose()

        return asyncio.run(_run())

    from sqlalchemy import create_engine

    engine = create_engine(url)
    try:
        with engine.connect() as conn:
            return _compare_sync(conn, metadata)
    finally:
        engine.dispose()


def main() -> int:
    metadata = _metadata(_load(METADATA_IMPORT))
    url = os.environ[DB_URL_ENV]
    diffs = [
        d for d in _diff(url, metadata) if not _op_name(d).startswith("modify_comment")
    ]
    tables = len(getattr(metadata, "tables", {}))
    print(f"tables in metadata: {tables}")
    print(
        f"structural diff after `alembic upgrade head` from empty: {len(diffs)} op(s)"
    )
    if diffs:
        print("\nThe migrated schema does NOT match the models:")
        for d in diffs:
            print(f"  {_op_name(d)}: {d}")
        print(
            "\nThe migration chain does not build what the models describe (a missing table shows as an "
            "ADDITIVE add_table — this is stricter than schema-drift on purpose). Write the migration; do "
            "NOT 'fix' this by editing the models to match a schema the chain cannot produce."
        )
        return 1
    print(
        f"✓ migrations build exactly what the models describe ({tables} tables, 0 drift)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
